In [ ]:
# import libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# read the csv file
df = pd.read_csv('../data/data.csv')

In [7]:
# check the last 5 rows of the dataset
df.tail()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [9]:
# check the columns and rows of the dataset 
rows, columns = df.shape
print(f"There are {rows} rows and {columns} columns")

There are 48842 rows and 15 columns

In [10]:
# check the dataset info 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  str
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  str
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  str
 6   occupation      47876 non-null  str
 7   relationship    48842 non-null  str
 8   race            48842 non-null  str
 9   sex             48842 non-null  str
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48568 non-null  str
 14  income          48842 non-null  str
dtypes: int64(6), str(9)
memory usage: 5.6 MB

In [ ]:
# identify the numerical
numerical = df.select_dtypes(include=['int64','float64']).columns.tolist()
numerical

['age',
 'fnlwgt',
 'education-num',
 'capital-gain',
 'capital-loss',
 'hours-per-week']

In [13]:
#  and categorical column
categorical = df.select_dtypes(include=['str','object']).columns.tolist()
categorical

['workclass',
 'education',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native-country',
 'income']

In [14]:
df[numerical]

       age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week
0       39   77516             13          2174             0              40
1       50   83311             13             0             0              13
2       38  215646              9             0             0              40
3       53  234721              7             0             0              40
4       28  338409             13             0             0              40
...    ...     ...            ...           ...           ...             ...
48837   39  215419             13             0             0              36
48838   64  321403              9             0             0              40
48839   38  374983             13             0             0              50
48840   44   83891             13          5455             0              40
48841   35  182148             13             0             0              60

[48842 rows x 6 columns]